# Generated by Django 5.2.4 on 2025-07-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateApplications',
            fields=[
                ('Affiliate_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_no', models.CharField(max_length=20)),
                ('Company', models.CharField(blank=True, max_length=200)),
                ('Title', models.CharField(blank=True, max_length=100)),
                ('Website', models.URLField(blank=True)),
                ('Business_phone', models.CharField(blank=True, max_length=20)),
                ('Is_payment', models.CharField(max_length=10)),
                ('Is_influencer', models.CharField(max_length=10)),
                ('Terms_accepted', models.BooleanField(default=False)),
                ('Submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Affiliate_applications',
            },
        ),
    ]
