# Generated by Django 5.2.2 on 2025-07-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliateapplications',
            name='Promotion_code',
        ),
    ]
