# Generated by Django 5.2.4 on 2025-07-30 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0019_alter_jobapplications_qualification_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial_news',
            fields=[
                ('News_id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=250)),
                ('Slug', models.SlugField(blank=True, unique=True)),
                ('Date_publish', models.DateField()),
                ('Content', models.TextField()),
                ('Summary', models.TextField(blank=True)),
                ('Active', models.BooleanField(default=True)),
                ('Added_on', models.DateTimeField(auto_now_add=True)),
                ('Thumbnail', models.ImageField(blank=True, upload_to='newsletter_thumb/')),
                ('Added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.signup')),
            ],
            options={
                'db_table': 'Financial_news',
            },
        ),
    ]
