# Generated by Django 5.2.4 on 2025-07-30 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_news_app', '0001_initial'),
        ('myapp', '0019_alter_jobapplications_qualification_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial_news',
            name='Added_by',
            field=models.ForeignKey(db_column='added_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.signup'),
        ),
    ]
