# Generated by Django 5.2.4 on 2025-07-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_news_app', '0002_alter_financial_news_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial_news',
            name='Thumbnail',
            field=models.ImageField(blank=True, upload_to='uploaded_files/newsletter_thumb/'),
        ),
    ]
