# Generated by Django 5.2.4 on 2025-08-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_news_app', '0003_alter_financial_news_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial_news',
            name='Thumbnail',
            field=models.ImageField(blank=True, upload_to='newsletter_thumb/'),
        ),
    ]
