# Generated by Django 5.2.4 on 2025-08-25 14:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_posting_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'blacklisted_tokens',
            },
        ),
        migrations.CreateModel(
            name='Lenders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lender_name', models.CharField(max_length=150)),
                ('Funding_type', models.CharField(max_length=250)),
                ('Funding_amount', models.CharField(max_length=25)),
                ('Min_credit_score', models.CharField(max_length=10)),
                ('Time_to_fund', models.CharField(max_length=50)),
                ('Terms', models.CharField(max_length=100)),
                ('Added_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Lenders_info',
            },
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('User_type', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer')], max_length=50)),
                ('Email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Password', models.CharField(max_length=250)),
                ('Date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'signup',
            },
        ),
        migrations.CreateModel(
            name='UserApplications',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Business_name', models.CharField(max_length=250)),
                ('Doing_business_as', models.CharField(blank=True, max_length=250, null=True)),
                ('Business_address', models.TextField()),
                ('Industry', models.CharField(max_length=250)),
                ('Tax_ID', models.CharField(max_length=12)),
                ('Entity', models.CharField(choices=[('llc', 'LLC'), ('corporation', 'Corporation'), ('sole_proprietor', 'Sole Proprietor'), ('partnership', 'Partnership')], max_length=50)),
                ('Business_Start_date', models.CharField(max_length=7)),
                ('Owner_First_Name', models.CharField(max_length=100)),
                ('Owner_Middle_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Owner_Last_Name', models.CharField(max_length=100)),
                ('Birth_Date', models.DateField()),
                ('Home_address', models.TextField(max_length=250)),
                ('Business_Email', models.EmailField(max_length=254)),
                ('Phone_no', models.CharField(max_length=10)),
                ('SSN', models.CharField(max_length=11)),
                ('Ownership', models.PositiveIntegerField()),
                ('Monthly_Revenue', models.PositiveIntegerField()),
                ('Funds_Requested', models.PositiveIntegerField()),
                ('Existing_loans', models.CharField(max_length=5)),
                ('First_time', models.CharField(default='Yes', max_length=5)),
                ('Applied_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'User_Applications',
            },
        ),
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('Application_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('First_name', models.CharField(max_length=150)),
                ('Last_name', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_no', models.CharField(max_length=15)),
                ('Expirence', models.CharField(choices=[('fresher', 'Fresher'), ('1-2', '1-2'), ('3-4', '3-4'), ('5-7', '5-7'), ('8-10', '8-10'), ('10+', '10+')], max_length=150)),
                ('Qualification_level', models.CharField(choices=[('undergrad', 'Under Graduation'), ('graduate', 'Graduation'), ('postgrad', 'Post Graduation')], max_length=200)),
                ('Major', models.CharField(max_length=200)),
                ('School_name', models.CharField(max_length=200)),
                ('Degree_year', models.IntegerField()),
                ('Expected_salary', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(max_length=50)),
                ('Resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('Applied_on', models.DateField(auto_now=True)),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job_posting_app.jobdetails')),
            ],
            options={
                'db_table': 'Job_applications',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.signup')),
            ],
            options={
                'db_table': 'Password_reset_token',
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_applications/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='myapp.userapplications')),
            ],
            options={
                'db_table': 'User_Docs',
            },
        ),
    ]
