# Generated by Django 5.2.2 on 2025-06-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('User_type', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer')], max_length=50)),
                ('Email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'signup',
            },
        ),
    ]
