# Generated by Django 5.2.2 on 2025-06-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Password',
            field=models.CharField(max_length=250),
        ),
    ]
