# Generated by Django 5.2.4 on 2025-09-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickApplication',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Business_name', models.CharField(max_length=250)),
                ('Industry', models.CharField(max_length=250)),
                ('Business_Start_date', models.CharField(max_length=7)),
                ('Owner_First_Name', models.CharField(max_length=100)),
                ('Owner_Last_Name', models.CharField(max_length=100)),
                ('Phone_no', models.CharField(max_length=10)),
                ('Credit_score', models.PositiveIntegerField()),
                ('Monthly_Revenue', models.PositiveIntegerField()),
                ('Funds_Requested', models.PositiveIntegerField()),
                ('Existing_loans', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'Quick_User_Applications',
            },
        ),
    ]
