# Generated by Django 5.2.4 on 2025-09-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_quickapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickapplication',
            name='Applied_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
