# Generated by Django 5.2.2 on 2025-06-10 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_signup_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='Date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
