# Generated by Django 5.2.4 on 2025-09-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_quickapplication_applied_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplications',
            name='Degree_year',
        ),
        migrations.RemoveField(
            model_name='jobapplications',
            name='Expected_salary',
        ),
        migrations.RemoveField(
            model_name='jobapplications',
            name='Major',
        ),
        migrations.RemoveField(
            model_name='jobapplications',
            name='Qualification_level',
        ),
        migrations.RemoveField(
            model_name='jobapplications',
            name='School_name',
        ),
    ]
