# Generated by Django 5.2.4 on 2025-09-15 19:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_jobapplications_degree_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickapplication',
            name='Business_Email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
