# Generated by Django 5.2.4 on 2025-09-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_quickapplication_business_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickapplication',
            name='Credit_score',
        ),
    ]
