# Generated by Django 5.2.2 on 2025-06-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_passwordresettoken_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='passwordresettoken',
            table='Password_reset_token',
        ),
    ]
