# Generated by Django 5.2.2 on 2025-06-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_passwordresettoken_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_name', models.CharField(max_length=250)),
                ('Doing_business_as', models.CharField(max_length=250)),
                ('Business_address', models.TextField()),
                ('Industry', models.CharField(max_length=250)),
                ('Tax_ID', models.CharField(max_length=12)),
                ('Entity', models.CharField(max_length=50)),
                ('Business_Start_date', models.DateField()),
                ('Owner_First_Name', models.CharField(max_length=100)),
                ('Owner_Middle_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Owner_Last_Name', models.CharField(max_length=100)),
                ('Birth_Date', models.DateField()),
                ('Home_address', models.TextField(max_length=250)),
                ('Business_Email', models.EmailField(max_length=254)),
                ('Phone_no', models.CharField(max_length=10)),
                ('SSN', models.CharField(max_length=9)),
                ('Ownership', models.PositiveIntegerField()),
                ('Monthly_Revenue', models.PositiveIntegerField()),
                ('Funds_Requested', models.PositiveIntegerField()),
                ('Existing_loans', models.CharField(max_length=5)),
                ('Documents', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('Applied_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'User_Applications',
            },
        ),
    ]
