# Generated by Django 5.2.2 on 2025-06-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_userapplications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapplications',
            name='id',
        ),
        migrations.AlterField(
            model_name='userapplications',
            name='SSN',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
