# Generated by Django 5.2.2 on 2025-06-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_userapplications_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplications',
            name='Business_Start_date',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='userapplications',
            name='Entity',
            field=models.CharField(choices=[('llc', 'LLC'), ('corporation', 'Corporation'), ('sole_proprietor', 'Sole Proprietor'), ('partnership', 'Partnership')], max_length=50),
        ),
    ]
