# Generated by Django 5.2.2 on 2025-06-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_userapplications_business_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplications',
            name='First_time',
            field=models.CharField(default='Yes', max_length=5),
        ),
        migrations.AlterField(
            model_name='userapplications',
            name='Documents',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/'),
        ),
    ]
