# Generated by Django 5.2.2 on 2025-06-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_userapplications_first_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplications',
            name='SSN',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
