# Generated by Django 5.2.2 on 2025-06-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_userapplications_ssn'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplications',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userapplications',
            name='SSN',
            field=models.CharField(max_length=11),
        ),
    ]
