# Generated by Django 5.2.4 on 2025-07-07 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting_app', '0005_alter_jobdetails_salary'),
        ('myapp', '0012_userapplications_id_alter_userapplications_ssn'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('Application_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('First_name', models.CharField(max_length=150)),
                ('Last_name', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_no', models.CharField(max_length=15)),
                ('Expirence', models.CharField(choices=[('fresher', 'Fresher'), ('1-2', '1-2'), ('3-4', '3-4'), ('5-7', '5-7'), ('8-10', '8-10'), ('10+', '10+')], max_length=150)),
                ('Qualification_level', models.CharField(choices=[('undergrad', 'Under Graduation'), ('grad', 'Graduation'), ('postgrad', 'Post Graduation')], max_length=200)),
                ('Major', models.CharField(max_length=200)),
                ('School_name', models.CharField(max_length=200)),
                ('Degree_year', models.IntegerField()),
                ('Expected_salary', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(max_length=50)),
                ('Resume', models.FileField(blank=True, null=True, upload_to='uploaded_files/resume/')),
                ('Applied_on', models.DateField(auto_now=True)),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job_posting_app.jobdetails')),
            ],
            options={
                'db_table': 'Job_applications',
            },
        ),
    ]
