# Generated by Django 5.2.2 on 2025-07-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_jobapplications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplications',
            name='Phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
