# Generated by Django 5.2.4 on 2025-07-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_blacklistedtoken'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blacklistedtoken',
            table='blacklisted_tokens',
        ),
    ]
