# Generated by Django 5.2.2 on 2025-07-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_jobapplications_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplications',
            name='Job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
