# Generated by Django 5.2.4 on 2025-07-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_blacklistedtoken_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lenders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lender_name', models.CharField(max_length=150)),
                ('Funding_type', models.CharField(max_length=250)),
                ('Funding_amount', models.CharField(max_length=25)),
                ('Min_credit_score', models.CharField(max_length=10)),
                ('Time_to_fund', models.CharField(max_length=50)),
                ('Terms', models.CharField(max_length=100)),
                ('Added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Lenders_info',
            },
        ),
    ]
