# Generated by Django 5.2.4 on 2025-07-14 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_lenders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lenders',
            name='Added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
