# Generated by Django 5.2.4 on 2025-07-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_lenders_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplications',
            name='Doing_business_as',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
