# Generated by Django 5.2.4 on 2025-07-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_userapplications_doing_business_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplications',
            name='Qualification_level',
            field=models.CharField(choices=[('undergrad', 'Under Graduation'), ('graduate', 'Graduation'), ('postgrad', 'Post Graduation')], max_length=200),
        ),
    ]
