# Generated by Django 5.2.4 on 2025-07-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_jobapplications_qualification_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplications',
            name='Documents',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/user_applications/'),
        ),
    ]
