# Generated by Django 5.2.4 on 2025-08-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_userapplications_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplications',
            name='Resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
        migrations.AlterField(
            model_name='userapplications',
            name='Documents',
            field=models.FileField(blank=True, null=True, upload_to='user_applications/'),
        ),
    ]
