# Generated by Django 5.2.4 on 2025-08-11 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_jobapplications_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapplications',
            name='Documents',
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_applications/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='myapp.userapplications')),
            ],
        ),
    ]
