# Generated by Django 5.2.4 on 2025-08-11 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_userapplications_documents_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='applicationdocument',
            table='User_Docs',
        ),
    ]
