# Generated by Django 5.2.4 on 2025-08-25 14:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('Job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Title', models.CharField(max_length=150)),
                ('Location', models.CharField(max_length=250)),
                ('Work_mode', models.CharField(choices=[('in_office', 'In office'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=50)),
                ('Job_type', models.CharField(choices=[('contract', 'Contract'), ('part_time', 'Part Time'), ('full_time', 'Full Time'), ('internship', 'Internship')], max_length=50)),
                ('Description', models.TextField()),
                ('Skills', models.TextField()),
                ('Salary', models.CharField(blank=True, max_length=12, null=True)),
                ('Email', models.EmailField(default=' info@lendeavorusa.com', max_length=254)),
                ('Added_by', models.EmailField(max_length=254)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Job_details',
            },
        ),
    ]
