# Generated by Django 5.2.2 on 2025-06-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='Salary',
            field=models.IntegerField(default=120000, max_length=12),
            preserve_default=False,
        ),
    ]
