# Generated by Django 5.2.2 on 2025-06-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting_app', '0003_alter_jobdetails_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='Salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
