# Generated by Django 5.2.2 on 2025-06-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting_app', '0004_alter_jobdetails_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='Salary',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
